name: trainlog_app
description: "Your online travel diary"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  currency_picker: ^2.0.21
  flutter_map: ^8.2.1
  csv: ^5.0.2
  http: ^1.4.0
  fluttertoast: ^8.2.4
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.6
  google_polyline_algorithm: ^3.1.0
  geodesy: ^0.10.2
  infinite_scroll_pagination: ^5.1.0
  dropdown_search: ^5.0.6
  diacritic: ^0.1.3
  country_picker: ^2.0.27
  fl_chart: ^1.0.0
  geolocator: ^13.0.1
  dio: ^5.4.0
  cookie_jar: ^4.0.6
  dio_cookie_manager: ^3.3.0
  html: ^0.15.4
  material_symbols_icons: ^4.2719.0
  step_progress: ^2.7.0
  duration: ^3.0.13
  unorm_dart: ^0.3.2
  lat_lng_to_timezone: ^0.2.0
  timezone: ^0.10.1
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.2.6
  flutter_html: ^3.0.0
  flutter_markdown_plus: ^1.0.5
  markdown_widget: ^2.3.2
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.14.4
  #dotted_line_flutter: ^2.1.8 # not used anymore, delete?
  #dotted_border: ^3.1.0
  shimmer: ^3.0.0
  share_plus: ^12.0.1
  package_info_plus: ^8.0.0
  const_date_time: ^1.2.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/i18n/
    - assets/logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/trainlog_icon.png"
  adaptive_icon_background: "assets/icon/trainlog_icon_background.png"
  adaptive_icon_foreground: "assets/icon/trainlog_icon_foreground.png"
  min_sdk_android: 21
  windows:
    generate: true
    icon_size: 256 # min:48, max:256, default: 48
